POST http://localhost:3333/events
Content-Type: application/json

{
    "title": 123,
    "details": null,
    "maximumAtendees": 1
}

###

POST http://localhost:3333/events/efaf8af1-dace-4651-96c3-73e172120e16/atendees
Content-Type: application/json

{
    "name": "Cayque Silva",
    "email": "cayque.silva3@edu.campinagrande.pb.gov.br"
}

###

GET http://localhost:3333/events/efaf8af1-dace-4651-96c3-73e172120e16

###

GET http://localhost:3333/atendees/7/badge

###

GET http://localhost:3333/atendees/7/check-in

###

GET http://localhost:3333/events/efaf8af1-dace-4651-96c3-73e172120e16/atendees